### ISSUE TITLE
Outputting a pyramid as a no-compression zip archive

### ISSUE THREAD

**Issue by sevaa** [niaid/tomojs-pytools#25]
I would like to have an option that the neuroglancer pyramid comes out ~~of `volume-to-precomputed-pyramid`~~ as a ZIP file with no compression, instead of a folder.

This will simplify things downstream considerably, when it comes to managing generated assets. "Every asset is a file" is a good invariant to have, and the neuroglancer pyramid is the odd one out. Wire level compression will be maintained by having the chunks gzipped, but since they are, there is no sense in zip-compressing them all over again. Transparent retrieval from the archive on reading is already in place. And with the recent revelation that the assets will have to be moved around on certain Hedwig operations, I'd much rather have one archive file than recurse through chunk directories.

The structure of the archive should mimic the structure of the pyramid folder - `info` on the root level, scale subdirectories under the root, gzipped chunk files in those. Please give the archive has a "zip" extension.

The asset path on the callback would be the path to the zip.

Thank you.

**Comment by blowekamp** [comment]
The `volume-to-precomputed-pyramid`is a third party tool from the neuroglancer-scripts  python package. Adding features/options and maintaining a fork is non-trivial.

The "directory to zip" functionality could be implemented as a reusable component/option of a workflow when the output is a directory.

**Comment by sevaa** [comment]
Doesn't have to be specifically in `volume-to-precomputed-pyramid`. Could be downstream.

**Comment by blowekamp** [comment]
Agreed, this is better handled as a requirement, and feature in the workflow than within one of the python tools provided by this project.
