### ISSUE TITLE
imagecodecs error while building tomojs-pytools

### ISSUE THREAD

**Issue by mbopfNIH** [niaid/tomojs-pytools#40]
While attempting to build tomojs-pytools on an M1 Mac running Monterey Version 12.6.2, I get the following error:
```
imagecodecs/_aec.c:756:10: fatal error: 'libaec.h' file not found
      #include "libaec.h"
               ^~~~~~~~~~
      1 warning and 1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> imagecodecs
```

Same error with both conda Python 3.9.15 and Homebrew Python 3.10.10

Hardware Overview:
```
 Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,1
  Chip:	Apple M1 Pro
  Total Number of Cores:	10 (8 performance and 2 efficiency)
  Memory:	16 GB
  System Firmware Version:	8419.60.44
  OS Loader Version:	7459.141.1
  Serial Number (system):	TNV664X05Y
  Hardware UUID:	B543DCDB-F3E3-51D8-88B2-6860F79AAF3A
  Provisioning UDID:	00006000-000C04C11A02401E
  Activation Lock Status:	Disabled
```

See attached file for complete run.
[imagecodes_error.txt](https://github.com/niaid/tomojs-pytools/files/10724825/imagecodes_error.txt)

**Comment by blowekamp** [comment]
The imagecodec package does not currently provide a Mac OSX ARM  binary. https://pypi.org/project/imagecodecs/

Building from the source appears to require a number of third party libraries.

So, the current work around is to use a x86_64 version on python on the M1 mac to use the existing binaries on PyPi.

**Comment by mbopfNIH** [comment]
The following steps worked for me:

1. Set up Rosetta Terminal
- Copied Terminal application in Finder->Applications to "Rosetta-Terminal" (requires admin)
- Right-clicked in "Rosetta-Terminal"->Get Info->Open using Rosetta  (requires admin)
- $ uname -m
x86_64

2. Using Rosetta Terminal:
- $ wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
- $ sh ./Miniconda3-latest-MacOSX-x86_64.sh
- Installed to $HOME/miniconda3-intel
- Activated miniconda3-intel environment
- Installed tomojs-pytools

The following links where helpful:
[Rosetta Terminal](https://www.courier.com/blog/tips-and-tricks-to-setup-your-apple-m1-for-development/)
[x86_64 miniconda install](https://towardsdatascience.com/how-to-install-miniconda-x86-64-apple-m1-side-by-side-on-mac-book-m1-a476936bfaf0)

**Comment by blowekamp** [comment]
I think the actionable item here is to update the sphinx docs, that this package is compatible with MacOS Rosetta, but not native M1.
